version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go mod download
      - run: go test -race -cover -coverprofile=coverage.txt .
      - run: go test -bench .
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
        path: coverage.txt
